// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: mode.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CommercialMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhysicalModes []*PhysicalMode `protobuf:"bytes,3,rep,name=physical_modes,json=physicalModes,proto3" json:"physical_modes,omitempty"`
}

func (x *CommercialMode) Reset() {
	*x = CommercialMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommercialMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommercialMode) ProtoMessage() {}

func (x *CommercialMode) ProtoReflect() protoreflect.Message {
	mi := &file_mode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommercialMode.ProtoReflect.Descriptor instead.
func (*CommercialMode) Descriptor() ([]byte, []int) {
	return file_mode_proto_rawDescGZIP(), []int{0}
}

func (x *CommercialMode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommercialMode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommercialMode) GetPhysicalModes() []*PhysicalMode {
	if x != nil {
		return x.PhysicalModes
	}
	return nil
}

type PhysicalMode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommercialMode []*CommercialMode `protobuf:"bytes,3,rep,name=commercial_mode,json=commercialMode,proto3" json:"commercial_mode,omitempty"`
}

func (x *PhysicalMode) Reset() {
	*x = PhysicalMode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhysicalMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalMode) ProtoMessage() {}

func (x *PhysicalMode) ProtoReflect() protoreflect.Message {
	mi := &file_mode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalMode.ProtoReflect.Descriptor instead.
func (*PhysicalMode) Descriptor() ([]byte, []int) {
	return file_mode_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalMode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalMode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalMode) GetCommercialMode() []*CommercialMode {
	if x != nil {
		return x.CommercialMode
	}
	return nil
}

var File_mode_proto protoreflect.FileDescriptor

var file_mode_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70,
	0x63, 0x22, 0x6e, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x0d, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0x70, 0x0a, 0x0c, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x4d,
	0x6f, 0x64, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x76, 0x69, 0x74, 0x69, 0x61, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x74, 0x69,
	0x61, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mode_proto_rawDescOnce sync.Once
	file_mode_proto_rawDescData = file_mode_proto_rawDesc
)

func file_mode_proto_rawDescGZIP() []byte {
	file_mode_proto_rawDescOnce.Do(func() {
		file_mode_proto_rawDescData = protoimpl.X.CompressGZIP(file_mode_proto_rawDescData)
	})
	return file_mode_proto_rawDescData
}

var file_mode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mode_proto_goTypes = []interface{}{
	(*CommercialMode)(nil), // 0: rpc.CommercialMode
	(*PhysicalMode)(nil),   // 1: rpc.PhysicalMode
}
var file_mode_proto_depIdxs = []int32{
	1, // 0: rpc.CommercialMode.physical_modes:type_name -> rpc.PhysicalMode
	0, // 1: rpc.PhysicalMode.commercial_mode:type_name -> rpc.CommercialMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mode_proto_init() }
func file_mode_proto_init() {
	if File_mode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommercialMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhysicalMode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mode_proto_goTypes,
		DependencyIndexes: file_mode_proto_depIdxs,
		MessageInfos:      file_mode_proto_msgTypes,
	}.Build()
	File_mode_proto = out.File
	file_mode_proto_rawDesc = nil
	file_mode_proto_goTypes = nil
	file_mode_proto_depIdxs = nil
}
