// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: weekPattern.proto

package rpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WeekPattern struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monday    bool `protobuf:"varint,1,opt,name=monday,proto3" json:"monday,omitempty"`
	Tuesday   bool `protobuf:"varint,2,opt,name=tuesday,proto3" json:"tuesday,omitempty"`
	Wednesday bool `protobuf:"varint,3,opt,name=wednesday,proto3" json:"wednesday,omitempty"`
	Thursday  bool `protobuf:"varint,4,opt,name=thursday,proto3" json:"thursday,omitempty"`
	Friday    bool `protobuf:"varint,5,opt,name=friday,proto3" json:"friday,omitempty"`
	Saturday  bool `protobuf:"varint,6,opt,name=saturday,proto3" json:"saturday,omitempty"`
	Sunday    bool `protobuf:"varint,7,opt,name=sunday,proto3" json:"sunday,omitempty"`
}

func (x *WeekPattern) Reset() {
	*x = WeekPattern{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weekPattern_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeekPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeekPattern) ProtoMessage() {}

func (x *WeekPattern) ProtoReflect() protoreflect.Message {
	mi := &file_weekPattern_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeekPattern.ProtoReflect.Descriptor instead.
func (*WeekPattern) Descriptor() ([]byte, []int) {
	return file_weekPattern_proto_rawDescGZIP(), []int{0}
}

func (x *WeekPattern) GetMonday() bool {
	if x != nil {
		return x.Monday
	}
	return false
}

func (x *WeekPattern) GetTuesday() bool {
	if x != nil {
		return x.Tuesday
	}
	return false
}

func (x *WeekPattern) GetWednesday() bool {
	if x != nil {
		return x.Wednesday
	}
	return false
}

func (x *WeekPattern) GetThursday() bool {
	if x != nil {
		return x.Thursday
	}
	return false
}

func (x *WeekPattern) GetFriday() bool {
	if x != nil {
		return x.Friday
	}
	return false
}

func (x *WeekPattern) GetSaturday() bool {
	if x != nil {
		return x.Saturday
	}
	return false
}

func (x *WeekPattern) GetSunday() bool {
	if x != nil {
		return x.Sunday
	}
	return false
}

var File_weekPattern_proto protoreflect.FileDescriptor

var file_weekPattern_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x65, 0x65, 0x6b, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0xc5, 0x01, 0x0a, 0x0b, 0x57, 0x65, 0x65,
	0x6b, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x64,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x75, 0x65, 0x73, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x74, 0x75, 0x65, 0x73, 0x64, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x65,
	0x64, 0x6e, 0x65, 0x73, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77,
	0x65, 0x64, 0x6e, 0x65, 0x73, 0x64, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x68, 0x75, 0x72,
	0x73, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x68, 0x75, 0x72,
	0x73, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x64, 0x61, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x72, 0x69, 0x64, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x61, 0x74, 0x75, 0x72, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x73, 0x61, 0x74, 0x75, 0x72, 0x64, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x6e, 0x64,
	0x61, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75, 0x6e, 0x64, 0x61, 0x79,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x76, 0x69, 0x74, 0x69, 0x61, 0x2f, 0x6e, 0x61, 0x76, 0x69, 0x74, 0x69, 0x61, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weekPattern_proto_rawDescOnce sync.Once
	file_weekPattern_proto_rawDescData = file_weekPattern_proto_rawDesc
)

func file_weekPattern_proto_rawDescGZIP() []byte {
	file_weekPattern_proto_rawDescOnce.Do(func() {
		file_weekPattern_proto_rawDescData = protoimpl.X.CompressGZIP(file_weekPattern_proto_rawDescData)
	})
	return file_weekPattern_proto_rawDescData
}

var file_weekPattern_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_weekPattern_proto_goTypes = []interface{}{
	(*WeekPattern)(nil), // 0: rpc.WeekPattern
}
var file_weekPattern_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weekPattern_proto_init() }
func file_weekPattern_proto_init() {
	if File_weekPattern_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_weekPattern_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeekPattern); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weekPattern_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weekPattern_proto_goTypes,
		DependencyIndexes: file_weekPattern_proto_depIdxs,
		MessageInfos:      file_weekPattern_proto_msgTypes,
	}.Build()
	File_weekPattern_proto = out.File
	file_weekPattern_proto_rawDesc = nil
	file_weekPattern_proto_goTypes = nil
	file_weekPattern_proto_depIdxs = nil
}
